### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'text' of null

### ISSUE THREAD

**Issue by andyyumiao** [casbin/casbin-dashboard#96]
when i want to add new model, and go to edit action button, got the error, see enclosure
![Xnip2020-08-20_14-07-45](https://user-images.githubusercontent.com/11346379/90723181-df059400-e2ee-11ea-8cba-75acfed82c94.jpg)
![Xnip2020-08-20_14-07-56](https://user-images.githubusercontent.com/11346379/90723187-e0cf5780-e2ee-11ea-83ab-0f474443f5cc.jpg)

**Comment by hsluoyz** [comment]
@BetaCat0 @438561537 please fix it.

**Comment by 438561537** [comment]
I will fix it on the sever

**Comment by 438561537** [comment]
The bug has been fixed. @hsluoyz

**Comment by hsluoyz** [comment]
@438561537 what PR or commit fixed this issue?

**Comment by 438561537** [comment]
@hsluoyz I will fix this issue in #94

**Comment by hsluoyz** [comment]
Refer to: https://github.com/casbin/casbin-dashboard/pull/94#issuecomment-677693228

**Comment by ZhengLin-Li** [comment]
Shall we close this issue as it has been finished? But it still appears in [Casbin Easy Tasks for Beginners/Student Applicants](https://github.com/orgs/casbin/projects/2#card-80720890), which is a little confiusing.
